const skillsData = [
  { "skill": "Java", "category": "Languages" },
  { "skill": "JavaScript", "category": "Languages" },
  { "skill": "TypeScript", "category": "Languages" },
  { "skill": "Python", "category": "Languages" },
  { "skill": "HTML", "category": "Languages" },
  { "skill": "CSS", "category": "Languages" },
  { "skill": "SQL", "category": "Languages" },
  { "skill": "Lua", "category": "Languages" },
  { "skill": "Arduino", "category": "Languages" },
  { "skill": "Swift", "category": "Languages" },
  { "skill": "C", "category": "Languages" },
  { "skill": "C++", "category": "Languages" },
  { "skill": "Bash", "category": "Languages" },
  { "skill": "React.js", "category": "Frameworks & Libraries" },
  { "skill": "Spring", "category": "Frameworks & Libraries" },
  { "skill": "Node.js", "category": "Frameworks & Libraries" },
  { "skill": "Express.js", "category": "Frameworks & Libraries" },
  { "skill": "JQuery", "category": "Frameworks & Libraries" },
  { "skill": "Django", "category": "Frameworks & Libraries" },
  { "skill": "JUnit", "category": "Frameworks & Libraries" },
  { "skill": "Godot", "category": "Frameworks & Libraries" },
  { "skill": "TensorFlow", "category": "Frameworks & Libraries" },
  { "skill": "Firebase", "category": "Frameworks & Libraries" },
  { "skill": "JSP", "category": "Frameworks & Libraries" },
  { "skill": "D3.js", "category": "Frameworks & Libraries" },
  { "skill": "ML5.js", "category": "Frameworks & Libraries" },
  { "skill": "p5.js", "category": "Frameworks & Libraries" },
  { "skill": "Three.js", "category": "Frameworks & Libraries" },
  { "skill": "Tailwind CSS", "category": "Frameworks & Libraries" },
  { "skill": "Bootstrap CSS", "category": "Frameworks & Libraries" },
  { "skill": "Git", "category": "Developer Tools & Platforms" },
  { "skill": "Figma", "category": "Developer Tools & Platforms" },
  { "skill": "Azure", "category": "Developer Tools & Platforms" },
  { "skill": "AWS", "category": "Developer Tools & Platforms" },
  { "skill": "Linux/Unix", "category": "Developer Tools & Platforms" },
  { "skill": "Heroku", "category": "Developer Tools & Platforms" },
  { "skill": "Adobe Creative Suite", "category": "Developer Tools & Platforms" },
  { "skill": "SOLIDWORKS", "category": "Developer Tools & Platforms" },
  { "skill": "AutoCAD", "category": "Developer Tools & Platforms" }
]